// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv8Ha-XB6tFvPOawmt06i0yBT679Qc0to',
    appId: '1:97150634296:web:fb4c6d4d070efe9d42d9cd',
    messagingSenderId: '97150634296',
    projectId: 'notes-bysarang',
    authDomain: 'notes-bysarang.firebaseapp.com',
    storageBucket: 'notes-bysarang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOUXVcTKEYGMuv05Bn44L_cG-pV5wmGN8',
    appId: '1:97150634296:android:4fbf725b1796010142d9cd',
    messagingSenderId: '97150634296',
    projectId: 'notes-bysarang',
    storageBucket: 'notes-bysarang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUV_ES4uyUV2eSKLLszRTqYUFsrF6HfhM',
    appId: '1:97150634296:ios:870a8ae208a8649642d9cd',
    messagingSenderId: '97150634296',
    projectId: 'notes-bysarang',
    storageBucket: 'notes-bysarang.appspot.com',
    iosBundleId: 'com.projects.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUV_ES4uyUV2eSKLLszRTqYUFsrF6HfhM',
    appId: '1:97150634296:ios:870a8ae208a8649642d9cd',
    messagingSenderId: '97150634296',
    projectId: 'notes-bysarang',
    storageBucket: 'notes-bysarang.appspot.com',
    iosBundleId: 'com.projects.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv8Ha-XB6tFvPOawmt06i0yBT679Qc0to',
    appId: '1:97150634296:web:5f482cbc2b6a6ae242d9cd',
    messagingSenderId: '97150634296',
    projectId: 'notes-bysarang',
    authDomain: 'notes-bysarang.firebaseapp.com',
    storageBucket: 'notes-bysarang.appspot.com',
  );
}
